<?php

namespace App\Services;

use App\Models\Cart;
use App\Models\Wishlist;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Str;

class GuestSessionService
{
    public static function getGuestToken(): string
    {
        // Primary: persistent 90-day cookie (exists after first response is received by browser)
        $token = request()->cookie('rayka_guest_token');

        if ($token) {
            // Keep session in sync so any request within the same browser tab always
            // resolves to the same cart, even before the cookie is echoed back.
            session(['rayka_guest_token' => $token]);

            return $token;
        }

        // Secondary: session fallback — bridges the gap on the *very first request* before
        // the Set-Cookie header has been returned to and re-sent by the browser.
        // This prevents a second, competing UUID being generated by concurrent requests
        // (e.g. the page GET + the /api/store-counts fetch that fires immediately after).
        $token = session('rayka_guest_token');

        if ($token) {
            // Re-queue the cookie in case it was cleared or never set yet.
            Cookie::queue(Cookie::make('rayka_guest_token', $token, 60 * 24 * 90));

            return $token;
        }

        // Brand-new guest: mint a stable UUID, persist in both session and cookie.
        $token = Str::uuid()->toString();
        session(['rayka_guest_token' => $token]);
        Cookie::queue(Cookie::make('rayka_guest_token', $token, 60 * 24 * 90)); // 90 days

        return $token;
    }

    public static function getCart(): Cart
    {
        if (Auth::check()) {
            $cart = Cart::firstOrCreate(['user_id' => Auth::id()]);

            return $cart;
        }

        $guestToken = self::getGuestToken();
        $cart = Cart::firstOrCreate(['guest_token' => $guestToken]);

        return $cart;
    }

    public static function mergeGuestDataToUser($user): void
    {
        // 1. Claim historical guest orders & addresses via Email/Mobile matching
        $unlinkedAddresses = \App\Models\Address::whereNull('user_id')
            ->where(function ($q) use ($user) {
                $q->where('email', $user->email)
                  ->orWhere('mobile', $user->mobile);
            })->get();

        foreach ($unlinkedAddresses as $addr) {
            $addr->update(['user_id' => $user->id]);
            \App\Models\Order::where('address_id', $addr->id)
                ->whereNull('user_id')
                ->update(['user_id' => $user->id]);
        }

        $guestToken = request()->cookie('rayka_guest_token');
        if (! $guestToken) {
            return;
        }

        // 2. Claim any remaining recent orders tied to the active guest session
        \App\Models\Order::whereNull('user_id')
            ->where('guest_token', $guestToken)
            ->update(['user_id' => $user->id]);

        // Merge Wishlist
        $guestWishlists = Wishlist::where('guest_token', $guestToken)->get();
        foreach ($guestWishlists as $gw) {
            Wishlist::firstOrCreate(
                ['user_id' => $user->id, 'product_id' => $gw->product_id],
                ['guest_token' => null]
            );
            $gw->delete();
        }

        // Merge Cart
        $guestCart = Cart::where('guest_token', $guestToken)->first();
        if ($guestCart) {
            $userCart = Cart::firstOrCreate(['user_id' => $user->id]);
            foreach ($guestCart->items as $item) {
                /** @var \App\Models\CartItem|null $existingItem */
                $existingItem = $userCart->items()
                    ->where('product_id', $item->product_id)
                    ->where('product_variant_id', $item->product_variant_id)
                    ->first();

                if ($existingItem) {
                    $existingItem->update([
                        'quantity' => $existingItem->quantity + $item->quantity,
                    ]);
                } else {
                    $item->update([
                        'cart_id' => $userCart->id,
                    ]);
                }
            }
            $guestCart->delete();
        }
    }
}
